apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-auth"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.services.auth.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.services.auth.port }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx200m -XX:+UseSerialGC -XX:TieredStopAtLevel=1"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "{{ .Values.infra.redis.port }}"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-config"
                  key: db-url-monolith
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: sneakverse-auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.services.auth.port }}