apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.services.frontend.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.services.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.port }}