apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: {{ .Values.services.gateway.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.services.gateway.port }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx256m"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-gateway"
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.services.gateway.port }}
      targetPort: {{ .Values.services.gateway.port }}