apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-gateway"
                port:
                  number: {{ .Values.services.gateway.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-frontend"
                port:
                  number: {{ .Values.services.frontend.port }}