apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-mysql-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-mysql"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.infra.mysql.image | quote }}
          ports:
            - containerPort: {{ .Values.infra.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: db-password
            - name: MYSQL_DATABASE
              value: "sneakverse"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-mysql-pvc"
---
apiVersion: v1
kind: Service
metadata:
  name: sneakverse-mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.infra.mysql.port }}
      targetPort: {{ .Values.infra.mysql.port }}