apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-orders"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.services.orders.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.services.orders.port }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx256m"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-config"
                  key: db-url-orders
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: db-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-config"
                  key: kafka-servers
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: jwt-secret
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-config"
                  key: jwk-set-uri
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: mail-password
---
apiVersion: v1
kind: Service
metadata:
  name: sneakverse-orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: {{ .Values.services.orders.port }}
      targetPort: {{ .Values.services.orders.port }}