apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
type: Opaque
stringData:
  db-username: {{ .Values.db.username | quote }}
  db-password: {{ .Values.db.password | quote }}
  jwt-secret: {{ .Values.security.jwtSecret | quote }}
  mail-password: {{ .Values.mail.password | quote }}