admin.email.from.address=vincenzolisi12@gmail.com
admin.email.from.name=Vincenzo Lisi
company.default.locale=en_US
company.default.time.zone=UTC
company.default.web.id=gmail.com
default.admin.email.address.prefix=vincenzolisi12
default.admin.first.name=Vincenzo
default.admin.last.name=Lisi
liferay.home=C:/Users/A858apulia/Desktop/SneakVerse/liferay-portal
setup.wizard.enabled=false
