#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/sneakverse-auth
osgi.jaxrs.application.select=(osgi.jaxrs.name=SneakVerseAuth.Rest)
osgi.jaxrs.resource=true